apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-full-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ZFlucKZ/idp-full-app.git
    targetRevision: main
    path: platform
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
