apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.manager: apiKey, login
  accounts.manager.enabled: 'true'

  accounts.frontend: apiKey, login
  accounts.frontend.enabled: 'true'

  accounts.backend: apiKey, login
  accounts.backend.enabled: 'true'
