apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextjs-app-dev
  namespace: argocd
spec:
  project: frontend
  source:
    repoURL: git@github.com:ZFlucKZ/nonprod-k8s-manifest-2.git
    targetRevision: main # branch
    path: dev/nextjs-app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
